export enum Generation {
  SEKOLAH_MINGGU = 'SEKOLAH MINGGU',
  PELAJAR = 'PELAJAR',
  MAHASISWA = 'MAHASISWA',
  KARAYAWAN = 'KARYAWAN',
  KELUARGA = 'KELUARGA',
  USIA_EMAS = 'USIA_EMAS',
  UMUM = 'UMUM',
}
